POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "user1",
  "password": "1234"
}

###
GET http://localhost:8080/systemInfo

###
GET http://localhost:8080/users?id=adfaferwrq24576
Authorization: ab79wyugdc9

###
GET http://localhost:8080/users?name=Joh
Authorization: 61oqoi28b9t

###
PUT http://localhost:8080/users
Authorization: 64ij8gj25il
Content-Type: application/json

{
  "age": 56,
  "email": "blabla@bla.com",
  "name": "bladiblabladi",
  "workingPosition": 4
}

###
DELETE http://localhost:8080/users?id=wisvzs8dbbl
Authorization: lsihagi82an

